import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Network Security App",
  description: "Generated by HumSad",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();

  // Check for system dark mode preference (optional)
  const prefersDarkMode = typeof window !== "undefined" && window.matchMedia("(prefers-color-scheme: dark)").matches;

  return (
    <SessionProvider session={session}>
      <html lang="en" className={prefersDarkMode ? "dark" : ""}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased text-foreground`}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}

